name: Download and Commit Data

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run workflow on'
        default: '1-get-data-from-api-and-webscrapping-tecniques'
        required: true
  schedule:
    # 17:00 en España en horario de invierno (CET = UTC+1 → 16:00 UTC)
    - cron: "30 17 * * *"
    # 17:00 en España en horario de verano (CEST = UTC+2 → 15:00 UTC)
    - cron: "30 16 * * *"

jobs:
  update-data:
    runs-on: ubuntu-latest
    # Solo correr si la rama es la secundaria que nos interesa
    if: github.ref == 'refs/heads/1-get-data-from-api-and-webscrapping-tecniques'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: '1-get-data-from-api-and-webscrapping-tecniques'

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Run main script
        run: |
          Rscript _aux/R/downloads/dataestur/dataestur_downloads.R

      - name: Commit and push changes if needed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          if [ -n "$(git status --porcelain data/)" ]; then
            git add data/
            git commit -m "Update data ($(date '+%Y-%m-%d %H:%M:%S'))"
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          else
            echo "No changes detected in data/, skipping commit."
