name: Download and Commit Data

on:
  workflow_dispatch:
  schedule:
    # 17:30 en España en horario de invierno (CET = UTC+1 → 16:30 UTC)
    - cron: "30 16 * * *"
    # 17:30 en España en horario de verano (CEST = UTC+2 → 15:30 UTC)
    - cron: "30 15 * * *"

jobs:
  update-data:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: '1-get-data-from-api-and-webscrapping-tecniques'

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Run main script
        run: |
          Rscript _aux/R/downloads/dataestur/dataestur_downloads.R

      - name: Commit and push changes if needed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          if [ -n "$(git status --porcelain data/)" ]; then
            git add data/
            git commit -m "Update data ($(date '+%Y-%m-%d %H:%M:%S'))"
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          else
            echo "No changes detected in data/, skipping commit."
          fi
            
        shell: bash
